<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>MiniPOS</AssemblyName>
		<RootNamespace>MiniPOS</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		
		<PackageReference Include="HIC.System.Windows.Forms.DataVisualization" Version="1.0.1" />
		
		<PackageReference Include="MySql.Data" Version="8.3.0" />
		<PackageReference Include="ClosedXML" Version="0.102.2" />
	</ItemGroup>
</Project>